name: ArtVoices
favicon: null
layout_spectrum: 0.21820080722682178
typography_spectrum: 0.08362918044440448
title: "Art that sells because it's seen and heard"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-61655831-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: null
    url: null
